/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:f3dd10f7-95db-4688-ab52-b20f9cd030ad",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_VynHEx7t3",
    "aws_user_pools_web_client_id": "3uo426bevo207l0ch73sb8a0pj",
    "oauth": {}
};


export default awsmobile;
